ALTER TABLE users
ADD zipCode VARCHAR(8) NOT NULL,
ADD address VARCHAR(255) NOT NULL,
ADD addressNumbeR VARCHAR(255),
ADD neighbourhood VARCHAR(255) NOT NULL,
ADD city VARCHAR(255) NOT NULL,
ADD state VARCHAR(255) NOT NULL;
